version: '2'

services:
    application:
        container_name: rogschedule_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: rogschedule_workspace
        image: rogteam/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: rogschedule_php-fpm
        image: rogteam/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: rogschedule_nginx
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "2021:80"
        links:
            - php-fpm
    data:
        container_name: rogschedule_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    logs:
        container_name: rogschedule_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: rogschedule_mysql
        image: mysql:5.7
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: rogschedule
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    mysql_test:
        container_name: rogschedule_mysql_test
        restart: always
        image: mysql:5.7
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: rogschedule_test
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: rogschedule_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8181:80"
        links:
            - "mysql:mysql"