version: 2
jobs:
  build:
    docker:
      - image: framgia/laravel-workspace
    steps:
      - checkout
      - run: cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:  composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # run test

      - run: phpcs --standard=Framgia app
      - run:
          name: Sending notification
          when: on_fail
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=
                [toall][info][title] build $CIRCLE_BUILD_NUM | STATUS : Fail [/title]
                - Repository name: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
                - Author: $CIRCLE_USERNAME
                - Branch: $CIRCLE_BRANCH
                - Commit/pull request link: https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1
                - Build link: https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM
                [/info]
                " \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM/messages"
            fi
      - run:
          name: Sending notification
          when: on_success
          command: |
            if [[ true ]];  then
              curl -X POST -H "X-ChatWorkToken: $CHATWORK_TOKEN" -d \
                "body=
                [toall][info][title] build $CIRCLE_BUILD_NUM | STATUS : Success [/title]
                - Repository name: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
                - Author: $CIRCLE_USERNAME
                - Branch: $CIRCLE_BRANCH
                - Commit/pull request link: https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1
                - Build link: https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM
                [/info]
                " \
                "https://api.chatwork.com/v2/rooms/$CHATWORK_ROOM/messages"
            fi
  deploy:
    docker:
      - image: circleci/php:7.2-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "$FINGER_KEY"
      - run:
          name: Install Deployer
          command: |
            curl -LO https://deployer.org/deployer.phar
            sudo mv deployer.phar /usr/local/bin/dep
            sudo chmod +x /usr/local/bin/dep
      - run:
          name: Deploy
          command: |
            if [ -z `ssh-keygen -F '35.240.156.156'` ]; then
              ssh-keyscan -H '35.240.156.156' >> ~/.ssh/known_hosts
            fi
            dep deploy -vvv


workflows:
  version: 2
  notify_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
