name: Pull_Comment
on:
  pull_request_review:
    types: [submitted]

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Comment
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          if [[ true ]];  then
            curl -X POST -H "X-ChatWorkToken: ${{ secrets.CW_TOKEN }}" -d \
              "body=
              [toall][info][title] New Request Submitted [/title]- New comment URL: ${{ github.event.review.html_url }}
          - Author: ${{ github.event.review.user.login }} ( ${{ github.event.review.user.html_url }} )
          - Submitted at: ${{ github.event.review.submitted_at }}[/info]
              " \
              "https://api.chatwork.com/v2/rooms/${{ secrets.CW_ROOM }}/messages"
          fi
